const products = [
  {
    name: "Birdhouse Plans",
    price: 10,
    category: 0,
    imageFileName: "images/birdhouse.jpg",
    imageUrl: "/images/birdhouse.jpg",
  },
  {
    name: "Workbench Plans",
    price: 20,
    category: 0,
    imageFileName: "images/workbench.jpg",
    imageUrl: "/images/workbench.jpg",
  },
  {
    name: "Chisel Set",
    price: 50,
    category: 1,
    imageFileName: "images/chisel.jpg",
    imageUrl: "/images/chisel.jpg",
  },
  {
    name: "Hand Saw",
    price: 30,
    category: 1,
    imageFileName: "images/handsaw.jpg",
    imageUrl: "/images/handsaw.jpg",
  },
  {
    name: "Cordless Drill",
    price: 120,
    category: 2,
    imageFileName: "images/drill.jpg",
    imageUrl: "/images/drill.jpg",
  },
  {
    name: "Circular Saw",
    price: 80,
    category: 2,
    imageFileName: "/images/circsaw.jpg",
    imageUrl: "/images/circsaw.jpg",
  },
  {
    name: "Clamps",
    price: 15,
    category: 3,
    imageFileName: "/images/clamps.jpg",
    imageUrl: "/images/clamps.jpg",
  },
  {
    name: "Wood Glue",
    price: 5,
    category: 3,
    imageFileName: "/images/woodglue.jpg",
    imageUrl: "/images/woodglue.jpg",
  },
  {
    name: "Screwdriver Set",
    price: 20,
    category: 1,
    imageFileName: "/images/scerwdriver.jpg",
    imageUrl: "/images/screwdriver.jpg",
  },
  {
    name: "Router",
    price: 100,
    category: 2,
    imageFileName: "/images/router.jpg",
    imageUrl: "/images/router.jpg",
  },
  {
    name: "Sander",
    price: 60,
    category: 2,
    imageFileName: "/images/sander.jpg",
    imageUrl: "/images/sander.jpg",
  },
  {
    name: "Table Saw",
    price: 200,
    category: 2,
    imageFileName: "/images/tablesaw.jpg",
    imageUrl: "/images/tablesaw.jpg",
  },
  {
    name: "Band Saw",
    price: 150,
    category: 2,
    imageFileName: "/images/bandsaw.jpg",
    imageUrl: "/images/bandsaw.jpg",
  },
  {
    name: "Drill Press",
    price: 80,
    category: 2,
    imageFileName: "/images/drillpress.jpg",
    imageUrl: "/images/drillpress.jpg",
  },
  {
    name: "Miter Saw",
    price: 100,
    category: 2,
    imageFileName: "/images/mitersaw.jpg",
    imageUrl: "/images/mitersaw.jpg",
  },
  {
    name: "Jigsaw",
    price: 60,
    category: 2,
    imageFileName: "/images/jigsaw.jpg",
    imageUrl: "/images/jigsaw.jpg",
  },
  {
    name: "Planer",
    price: 150,
    category: 2,
    imageFileName: "/images/planer.jpg",
    imageUrl: "/images/planer.jpg",
  },
  
];

module.exports = products;
